config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'



  end

  root to: 'tickets#index'

  scope "(:locale)", locale: /en/ do
    resources :tickets do
      resources :comments
    end
  end

  resources :tickets do
    resources :versions, only: [:destroy] do
      member do
        get :diff, to: 'versions#diff'
      end
    end
  end

  scope path: 'ticket/:id', controller: :tickets do
    put '/:status_of_ticket', to: 'tickets#resolved', status_of_ticket: /resolved/, as: :resolved
    put '/:status_of_ticket', to: 'tickets#take_in_work', status_of_ticket: /take_in_work/, as: :take_in_work
    put '/:status_of_ticket', to: 'tickets#closed', status_of_ticket: /closed/, as: :closed
  end

  get '/:locale' => 'tickets#index'

  mount ActionCable.server => '/cable'
  
end

app/models/ticket.rb
# Ticket model
class Ticket < ApplicationRecord
  after_create :send_create_telegram_message
  after_update :send_update_telegram_message
  after_destroy :send_destroy_telegram_message

  belongs_to :user, foreign_key: 'user_id'
  has_paper_trail
  has_many :comments, dependent: :destroy

  enum type_of_ticket: %i[repaire service_request permisiion_request]
  enum status_of_ticket: %i[newly_created in_progress closed resolved]
  enum responsible_unit: %i[repair service security]
  enum priority: %i[low middle high]

  validates :title, length: { minimum: 10, maximum: 100 }, presence: true, uniqueness: true
  validates :detailed_description, length: { minimum: 20, maximum: 1000 }
  validates :deadline, :type_of_ticket, :responsible_unit, :priority, presence: true

  mount_uploader :attachment, AttachmentUploader

  filterrific(
    default_filter_params: { sorted_by: 'created_at_desc' },
    available_filters: %w[
      sorted_by
      search_query
      with_type_of_ticket
      with_status_of_ticket
      with_responsible_unit
      with_priority
      with_user_id
      with_created_at_gte
    ]
  )

  self.per_page = 10

  scope :search_query, lambda { |query|
    return nil  if query.blank?
    # condition query, parse into individual keywords
    terms = query.downcase.split(/\s+/)
    # replace "*" with "%" for wildcard searches,
    # append '%', remove duplicate '%'s
    terms = terms.map { |e|
      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    # configure number of OR conditions for provision
    # of interpolation arguments. Adjust this if you
    # change the number of OR conditions.
    num_or_conditions = 2
    where(
      terms.map {
        or_clauses = [
          "LOWER(tickets.title) LIKE ?",
          "LOWER(tickets.detailed_description) LIKE ?",
        ].join(' OR ')
        "(#{ or_clauses })"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conditions }.flatten
    )

  }

  scope :sorted_by, lambda { |sort_option|
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^created_at_/
      order("tickets.created_at #{ direction }")
    when /^updated_at_/
        order("tickets.updated_at #{ direction }")
    when /^title_/
      order("LOWER(tickets.title) #{ direction }")
    when /^deadline_/
        order("tickets.deadline #{ direction }")
    when /^type_of_ticket_/
        order("tickets.type_of_ticket #{ direction }")
    when /^status_of_ticket_/
        order("tickets.status_of_ticket #{ direction }")
    when /^responsible_unit_/
        order("tickets.responsible_unit #{ direction }")
    when /^priority_/
        order("tickets.priority #{ direction }")
    when /^author_/
      order("LOWER(users.username) #{ direction }").includes(:user).references(:user)
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }

  scope :with_type_of_ticket, lambda { |type_of_tickets|
    return nil if type_of_tickets == ['']
    where(type_of_ticket: [*type_of_tickets])
  }

  scope :with_status_of_ticket, lambda { |status_of_tickets|
    return nil if status_of_tickets == ['']
    where(status_of_ticket: [*status_of_tickets])
  }

  scope :with_responsible_unit, lambda { |responsible_units|
    return nil if responsible_units == ['']
    where(responsible_unit: [*responsible_units])
  }
  
  scope :with_priority, lambda { |priority|
    return nil if priority == ['']
    where(priority: [*priority])
  }

  scope :with_user_id, lambda { |user_ids|
    return nil if user_ids == ['']
    where(:user_id => [*user_ids])
  }
  scope :with_created_at_gte, lambda { |ref_date|
    return nil if created_at_gtes == ['']
    where('tickets.created_at >= ?', ref_date)
  }

  delegate :username, :to => :user, :prefix => true

  def self.options_for_sorted_by
    [
      ['Title (a-z)', 'title_asc'],
      ['Title (z-a)', 'title_desc'],
      ['Creation date (newest first)', 'created_at_desc'],
      ['Creation date (oldest first)', 'created_at_asc'],
      ['Author (a-z)', 'author_asc'],
      ['Author (z-a)', 'author_desc']

    ]
  end

  def decorated_created_at
    created_at.to_date.to_s(:long)
  end

  private

   def ticket_author
     user = User.find_by(id: user_id)
     user.username
   end

   def send_create_telegram_message
     TelegramBotJob.new.perform_async_create(id, title, ticket_author)
   end

   def send_update_telegram_message
     TelegramBotJob.new.perform_async_update(id, title, ticket_author)
   end

   def send_destroy_telegram_message
     TelegramBotJob.new.perform_async_destroy(id, title, ticket_author)
   end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :find_ticket, only: %i[show edit update destroy take_in_work resolved closed]
  before_action :owned_ticket, only: %i[edit update destroy]
  before_action :ticket, only: :new

  def index
    (@filterrific = initialize_filterrific(
      Ticket,
      params[:filterrific],
      select_options: {
        sorted_by: Ticket.options_for_sorted_by,
        with_type_of_ticket: %w[repaire service_request permisiion_request],
        with_status_of_ticket: %w[newly_created in_progress closed resolved],
        with_responsible_unit: %w[repair service security],
        with_priority: %w[low middle high],
        with_user_id: User.options_for_select
      },
      default_filter_params: {},
      available_filters: %i[sorted_by search_query with_type_of_ticket with_status_of_ticket with_responsible_unit with_priority with_user_id]
    )) || return

    @tickets = @filterrific.find.page(params[:page])
    respond_to do |format|
      format.html
      format.js
    end
  rescue ActiveRecord::RecordNotFound => e
    logger.debug("Had to reset filterrific params: #{e.message}")
    redirect_to(reset_filterrific_url(format: :html)) && return
  end

  def show
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new; end

  def create
    @ticket = current_user.tickets.new(ticket_params)
    @ticket.status_of_ticket = :newly_created

    if @ticket.save
      UserMailer.ticket_email(@current_user).deliver
      flash[:success] = 'Ticket created'
      redirect_to tickets_path
    else
      flash[:warning] = 'Ticket not created'
      render :new
    end
  end

  def edit; end

  def update
    if @ticket.update(ticket_params)
      flash[:success] = 'Ticket updated'
      redirect_to tickets_path
    else
      flash[:warning] = 'Ticket not updated'
      render 'edit'
    end
  end

  def destroy
    if @ticket.destroy
      flash[:success] = 'Ticket deleted'
      redirect_to tickets_path
    else
      flash[:warning] = "Ticket doesn't exist"
    end
  end

  def take_in_work
    if current_user.executor? && @ticket.newly_created?
      @ticket.update(executor: current_user.email, status_of_ticket: 'in_progress')
      find_user_and_send_email

      redirect_to ticket_path
    else
      flash[:warning] = 'Action is not avalible'

      redirect_to root_path
    end
  end

  def resolved
    if current_user.email == @ticket.executor && @ticket.in_progress?
      @ticket.update(status_of_ticket: 'resolved')
      find_user_and_send_email

      redirect_to ticket_path
    else
      flash[:warning] = 'Action is not avalible'

      redirect_to root_path
    end
  end

  def closed
    if current_user.id == @ticket.user_id && @ticket.in_progress?
      @ticket.update(status_of_ticket: 'closed')
      find_executor_and_send_email

      redirect_to ticket_path
    else
      flash[:warning] = 'Action is not avalible'

      redirect_to root_path
    end
  end

  private

  def find_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:title, :detailed_description, :type_of_ticket, :executor, :deadline,
                                   :history, :status_of_ticket, :responsible_unit, :attachment, :priority)
  end

  def ticket
    @ticket ||= Ticket.new
  end

  def owned_ticket
    if current_user.id != @ticket.user_id
      flash[:alert] = "That ticket doesn't belong to you!"
      redirect_to root_path
    end
  end

  def find_user_and_send_email
    @user = User.find_by(id: @ticket.user_id)
    UserMailer.take_in_work_email(@user, @ticket).deliver
  end

  def find_executor_and_send_email
    @executor = User.find_by(email: @ticket.executor)
    UserMailer.closed_email(@executor, @ticket).deliver
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
  def ticket_of_current_user?(ticket)
    ticket.user_id == current_user.id
  end

  def diff(content1, content2)
     changes = Diffy::Diff.new(content1, content2,
                               include_plus_and_minus_in_html: true,
                               include_diff_info: true)
     changes.to_s.present? ? changes.to_s(:html).html_safe : 'No Changes'
  end
end

app/views/tickets/_list.html.haml
#filterrific_results
  %div
    = page_entries_info tickets
  .panel.panel-default
    %h1.panel-heading= t('tickets._list.list_of_tickets')
    .panel-body
      %table.table.table-striped.table-hover.table-condensed
        %tr
        %th= filterrific_sorting_link(@filterrific, :status_of_ticket)
        %th= filterrific_sorting_link(@filterrific, :type_of_ticket)
        %th= filterrific_sorting_link(@filterrific, :title)
        -# %th= t('tickets._list.detailed_description')
        %th= filterrific_sorting_link(@filterrific, :responsible_unit)
        %th= filterrific_sorting_link(@filterrific, :author)
        -# %th= t('tickets._list.executor')
        %th= filterrific_sorting_link(@filterrific, :deadline)
        %th= filterrific_sorting_link(@filterrific, :priority)
        %th= t('tickets._list.attachment')
        %th= filterrific_sorting_link(@filterrific, :created_at)
        %th= filterrific_sorting_link(@filterrific, :updated_at)
        %th= t('tickets._list.available_actions')
        - @tickets.each do |ticket|
          %tr
            %td= ticket.status_of_ticket
            %td= ticket.type_of_ticket
            %td= ticket.title
            -# %td= ticket.detailed_description
            %td= ticket.responsible_unit
            %td
              = ticket.user.username
              = ticket.user.email
            -# %td= ticket.executor
            %td= ticket.deadline
            %td= ticket.priority
            %td
              - if ticket.attachment?
                = image_tag(ticket.attachment_url(:thumb))
                %br
                = link_to 'Download file', ticket.attachment.url
            %td= ticket.created_at
            %td= ticket.updated_at
            %td
              = button_to "Show ticket", ticket_path(@user, ticket), method: :get
              %br
              - if ticket_of_current_user?(ticket)
                = button_to "Edit ticket", edit_ticket_path(@user, ticket), method: :get
                %br
                = button_to "Delete ticket", ticket_path(@user, ticket), method: :delete, data: { confirm: 'Are you sure?' }
= will_paginate tickets

app/views/tickets/_versions.html.erb
<h2>History of ticket changes</h2>

<table class='table'>
  <thead>
    <tr>
      <th>Index</th>
      <th>Date</th>
      <th>Author</th>
      <th>Event</th>
      <th>Changes</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%if @ticket.versions.length > 1 %>
      <% @ticket.versions[1..-1].reverse.each do |version| %>
        <tr>
          <td><%= version.index %></td>
          <td><%= version.created_at %></td>
          <td><%= User.find_by(id: version.whodunnit).username %></td>
          <td><%= version.event.humanize %></td>
          <td><%= link_to 'Changes', diff_ticket_version_path(ticket, version) %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/tickets/edit.html.haml
= form_with(model: @ticket, url: ticket_path, method: :patch, local: true) do |form|
  - if @ticket.errors.any?
    #error_explanation
      %h2
        = pluralize(@ticket.errors.count, "error")
        prohibited
        this ticket from being saved:
      %ul
        - @ticket.errors.full_messages.each do |msg|
          %li= msg
  .container
    .row
      .col-md-7.col-md-offset-2
        .panel.panel-default
          .panel-heading
            %p.lead Editing ticket
          .panel-body
            .form-group
              = form.label :title
              %br/
              = form.text_field :title, :maxlength=>"75"
            .form-group
              = form.label :type_of_ticket
              %br/
              = form.select :type_of_ticket, Ticket.type_of_tickets.keys
            .form-group
              = form.label :responsible_unit
              %br/
              = form.select :responsible_unit, Ticket.responsible_units.keys
            .form-group
              = form.label :priority
              %br/
              - if current_user.tickets.newly_created.count + current_user.tickets.in_progress.count >= 10
                = form.select :priority, Ticket.priorities.keys.first(1)
              - elsif current_user.tickets.newly_created.count + current_user.tickets.in_progress.count > 5
                = form.select :priority, Ticket.priorities.keys.first(2)
              - else
                = form.select :priority, Ticket.priorities.keys
            .form-group
              = form.label :detailed_description
              %br/
              = form.text_area :detailed_description, size: "200x10", class: "ckeditor", id: "detailed_description"
              = form.label :deadline
              %br/
              = form.date_field :deadline
            .form-group
              = form.label :attachment
              %br/
              = form.file_field :attachment
            %p
              = form.submit "Update", class: 'btn btn-primary'
            = link_to 'Back', tickets_path
:javascript
  CKEDITOR.replace('detailed_description')

app/views/tickets/index.html.haml
.panel.panel-default
  %h3.panel-heading= t('tickets.index.filter_of_tickets')
  = form_for_filterrific @filterrific do |f|
    %div
      Search
      = f.text_field :search_query,
                         :class => 'filterrific-periodically-observed'
      %p
      = t('tickets.index.filter_type')
      \#{f.select( :with_type_of_ticket, @filterrific.select_options[:with_type_of_ticket], { include_blank: '- Any -', multiple: true } )}

      = t('tickets.index.filter_status')
      \#{f.select( :with_status_of_ticket, @filterrific.select_options[:with_status_of_ticket], { include_blank: '- Any -', multiple: true } )}

      = t('tickets.index.filter_responsible_unit')
      \#{f.select( :with_responsible_unit, @filterrific.select_options[:with_responsible_unit], { include_blank: '- Any -', multiple: true } )}

      Priority
      \#{f.select( :with_priority, @filterrific.select_options[:with_priority], { include_blank: '- Any -', multiple: true } )}

      Author
      \#{f.select( :with_user_id, @filterrific.select_options[:with_user_id], { include_blank: '- Any -', multiple: true } )}
      
      Sorted by
      \#{f.select( :sorted_by, @filterrific.select_options[:sorted_by] )}

    %div
      = link_to(                 |
          'Reset filters',       |
          reset_filterrific_url, |
        )
    = render_filterrific_spinner
  = render(                         |
      partial: 'tickets/list',      |
      locals: { tickets: @tickets } |
    )                               |

app/views/tickets/new.html.haml
= form_with scope: :ticket, url: tickets_path, local: true do |form|
  - if @ticket.errors.any?
    #error_explanation
      %h2
        = pluralize(@ticket.errors.count, "error")
        prohibited
        this ticket from being saved:
      %ul
        - @ticket.errors.full_messages.each do |msg|
          %li= msg
  .container
    .row
      .col-md-7.col-md-offset-2
        .panel.panel-default
          .panel-heading
            %p.lead New ticket
          .panel-body
            .form-group
              = form.label :title
              %br/
              = form.text_field :title, :maxlength=>"75"
            .form-group
              = form.label :type_of_ticket
              %br/
              = form.select :type_of_ticket, Ticket.type_of_tickets.keys, { include_blank: '- Choose type -', multiple: true }
            .form-group
              = form.label :responsible_unit
              %br/
              = form.select :responsible_unit, Ticket.responsible_units.keys, { include_blank: '- Choose unit -', multiple: true }
            .form-group
              = form.label :priority
              %br/
              - if current_user.tickets.newly_created.count + current_user.tickets.in_progress.count >= 10
                = form.select :priority, Ticket.priorities.keys.first(1), { include_blank: '- Choose priority -', multiple: true }
              - elsif current_user.tickets.newly_created.count + current_user.tickets.in_progress.count > 5
                = form.select :priority, Ticket.priorities.keys.first(2), { include_blank: '- Choose priority -', multiple: true }
              - else
                = form.select :priority, Ticket.priorities.keys, { include_blank: '- Choose priority -', multiple: true }

            %p
            .form-group
              = form.label :detailed_description
              %br/
              = form.text_area :detailed_description, size: "200x10", class: "ckeditor", id: "detailed_description"
            .form-group
              = form.label :deadline
              %br/
              = form.date_field :deadline, value: Time.now.strftime('%Y-%m-%d')
            .form-group
              = form.label :attachment
              %br/
              = form.file_field :attachment
            %p
              = form.submit "Save", class: 'btn btn-primary'
            %p
            = link_to 'Back', tickets_path
:javascript
  CKEDITOR.replace('detailed_description')

app/views/tickets/show.html.haml
.container
  .row
    .col-md-8.col-md-offset-2
      .panel.panel-default
        .panel-heading
          .lead Ticket params
        .panel-body
          .form-group
            %p
            %strong Title:
            = @ticket.title
          .form-group
            %p
              %strong Status of ticket:
              = @ticket.status_of_ticket
          .form-group
            %p
              %strong Type of ticket:
              = @ticket.type_of_ticket.humanize
          .form-group
            %p
              %strong Detailed description:
              = @ticket.detailed_description.html_safe
          .form-group
            %p
              %strong Responsible unit:
              = @ticket.responsible_unit.humanize
          .form-group
            %p
              %strong Author:
              = @ticket.user.email
          .form-group
            %p
              %strong Executor:
              = @ticket.executor
          .form-group
            %p
              %strong Priority:
              = @ticket.priority
          .form-group
            %p
              %strong Deadline:
              = @ticket.deadline
          .form-group
            %h4 Comments
            .comments{:id => "comments_#{@ticket.id}"}
              - if @ticket.comments
                = render @ticket.comments, ticket: @ticket
          .form-group
            %h4 Add a comment:
            = render 'comments/form'
          .form-group
            - if current_user.email == @ticket.executor && @ticket.in_progress?
              = button_to 'Resolved', resolved_path(@ticket, status_of_ticket: 'resolved'), method: :put
            -elsif current_user.executor? && @ticket.newly_created?
              = button_to 'Take in work', take_in_work_path(@ticket, status_of_ticket: 'take_in_work'), method: :put
            -elsif current_user.id == @ticket.user_id && @ticket.in_progress?
              = button_to 'Close', closed_path(@ticket, status_of_ticket: 'closed'), method: :put
          .form-group
            = render 'chat_rooms/form'
          .form-group
            = render 'versions', ticket: @ticket
          .form-group
            = link_to 'Back', tickets_path