config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'



  end

  root to: 'tickets#index'

  scope "(:locale)", locale: /en/ do
    resources :tickets do
      resources :comments
    end
  end

  resources :tickets do
    resources :versions, only: [:destroy] do
      member do
        get :diff, to: 'versions#diff'
      end
    end
  end

  scope path: 'ticket/:id', controller: :tickets do
    put '/:status_of_ticket', to: 'tickets#resolved', status_of_ticket: /resolved/, as: :resolved
    put '/:status_of_ticket', to: 'tickets#take_in_work', status_of_ticket: /take_in_work/, as: :take_in_work
    put '/:status_of_ticket', to: 'tickets#closed', status_of_ticket: /closed/, as: :closed
  end

  get '/:locale' => 'tickets#index'

  mount ActionCable.server => '/cable'
  
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ticket_and_version, only: [:diff, :destroy]

  def diff
  end

  private

  def set_ticket_and_version
    @ticket = Ticket.find(params[:ticket_id])
    @version = @ticket.versions.find(params[:id])
  end
end

app/views/versions/diff.html.erb
<div class='row mt'>
  <div class='col-sm-12'>
    <h2><%= "Changes between Version #{@version.id} and Current Version" %></h2>
    <style><%= Diffy::CSS %></style>
    <div class='well diff'>
      <p>
        <strong>Title:</strong>
        <%= diff(@version.reify.title, @ticket.title) %>
      </p>
      <p>
        <strong>Detailed description:</strong>
        <%= diff(@version.reify.detailed_description, @ticket.detailed_description) %>
      </p>
      <p>
        <strong>Type of ticket:</strong>
        <%= diff(@version.reify.type_of_ticket, @ticket.type_of_ticket) %>
      </p>
      <p>
        <strong>Responsible unit:</strong>
        <%= diff(@version.reify.responsible_unit, @ticket.responsible_unit) %>
      </p>
      <p>
        <strong>Deadline:</strong>
        <%= diff(@version.reify.deadline, @ticket.deadline) %>
      </p>
      <p>
        <strong>Status of ticket:</strong>
        <%= diff(@version.reify.status_of_ticket, @ticket.status_of_ticket) %>
      </p>
    </div>
  </div>
</div>
<div class='fr'>
  <%= link_to 'Back', ticket_path(@ticket), class: 'btn btn-danger' %>
</div>